[package]
name = "lsp"
version = "0.0.0"
authors = ["Pig Fang <g-plane@hotmail.com>"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1"
parking_lot = { version = "0.11.2", features = ["wasm-bindgen"] }
serde-wasm-bindgen = "0.6"
wasm-bindgen = "0.2"
wat_service = "0.1"

[profile.release]
opt-level = "s"
